# Generated by Django 3.2.7 on 2021-09-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210909_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
            preserve_default=False,
        ),
    ]
